### ISSUE TITLE
Compilation issue with Teensy 4.0 and 4.1

### ISSUE THREAD

**Issue by darve** [vindar/tgx#1]
Hey there, blown away by your work! Running into an issue compiling some of the TGX examples though, I wonder if this is an issue you've seen before?

![image](https://user-images.githubusercontent.com/1042366/118630231-40975800-b7c6-11eb-8319-a64a61178c78.png)

Apologies if this is an error on my part, thanks for building such amazing libraries for the Teensy!

Teensyduino v1.53
Libraries (TGX, ili9341_t4, ili9341_t3n) all latest
Running on latest MacOS

Dave

**Comment by vindar** [comment]
Hi, 

Yes, apparently the function `extmem_malloc()` and `extmem_free()` used to allocate memory on extram for teensy 4.1 are not yet defined in teensyduino 1.53 (there should be a file called `extmem.c` located in `/avr/cores/teensy4`). 

However, it should compile fine with newer versions: I am currently using [teensyduino 1.54 beta 9](https://forum.pjrc.com/threads/67252-Teensyduino-1-54-Beta-9).

**Comment by darve** [comment]
Amazing, I just downloaded the beta and the examples work perfectly. You are an absolute genius - I have no idea how you managed to get such incredibly performance out of this display - BIG respect.

I found myself playing around with your ili9341_t4 library and different canvas libraries to draw to the framebuffer - TGX seems like a much nicer way of doing things. Cheers!

Now I just need to figure out how to make nice anti-aliased fonts...

**Comment by vindar** [comment]
Thanks ! 
I am glad you like it. Have fun with it :-)
I did not test these libraries very thoroughly so there are probably many bugs to be found but I will try to solve them over time...

**Comment by vindar** [comment]
Hello, 

I do not know if you are still interested in antialiased fonts: I created a library <a href="https://github.com/vindar/tgx-font/">tgx-font</a> that collects anti-aliased fonts that can be used with the tgx library.  There is also a script which contains instructions on how to make you own anti-aliased fonts from usual .ttf format (thanks to a previous work by <a href="https://github.com/projectitis/packedbdf">projectitis</a>). 

I also added quite a few methods for 2D drawing with tgx (circle, ellipse and anti-aliased drawing with support for alpha-blending)...

**Comment by darve** [comment]
Oh my word this sounds absolutely fantastic! Thanks for keeping me in the loop, I'm very excited to try it out!

**Comment by darve** [comment]
This is really interesting - my current project has actually moved me away from ili9341 as I am using a little round ST7789 display instead because the form factor makes better sense for the project, but I've been very much missing the amazing performance from your library! I was wondering about maybe trying to have a crack at seeing if I could get tgx to work on that display... I'll do my best!
