### ISSUE TITLE
TGX_SHADER_NOZBUFFER can't be used

### ISSUE THREAD

**Issue by belm0** [vindar/tgx#11]
It doesn't seem possible to use TGX_SHADER_NOZBUFFER exclusively, because the `Renderer3D` constructor calls `setZbuffer(nullptr)`, triggering a static assert.

```c++
const int SHADERS = TGX_SHADER_PERSPECTIVE | TGX_SHADER_NOZBUFFER | TGX_SHADER_FLAT | TGX_SHADER_NOTEXTURE;
Renderer3D<RGB565, 140, 200, SHADERS> renderer;
```
```
Renderer3D.h:333:13: error: static assertion failed: shader TGX_SHADER_ZBUFFER must be enabled to use setZbuffer()
             static_assert(TGX_SHADER_HAS_ZBUFFER(ENABLED_SHADERS), "shader TGX_SHADER_ZBUFFER must be enabled to use setZbuffer()");
             ^
```

**Comment by vindar** [comment]
Hi,

Indeed, I must have added this bug  that when I cleaned up the initialization code. There might be more as I have not tested the library very thoroughly when the flag TGX_SHADER_NOZBUFFER is set. 

Just just updated the code to remove this error.  Thanks for the report.

**Comment by belm0** [comment]
thank you!
