### ISSUE TITLE
ESP32 3D CONVERTER

### ISSUE THREAD

**Issue by Niutonian** [vindar/tgx#15]
Hello, great library.
I´ve been successfully run the ESP32 example. 
But I was wondering what method did you use to convert the models in .H files?

Thank you

**Comment by vindar** [comment]
Hi, 

There are Python scripts in the tools/ sub-directory which are the one I used to create all the models in the examples:

- texture_2_h.py converts an image (jpeg, png...) to a TGX::Image that can be used as a texture image. 
- obj_2_h.py converts a 3d model in .obj format to one (or more) meshes in a .h file that can be used directly with tgx.

there is no documentation for using these tools but it should be quite simple anyway. I plan to create better conversion tools at some point but I have no timeline for that yet...

**Comment by Niutonian** [comment]
Thank you for the quick reply. 
I will give those scripts a try.

Keep up the great work!! +1

**Comment by Niutonian** [comment]
Sorry, let me reopen this issue.
One last question about the python script.
What is the syntax to import the obj file into it?
Thank you

**Comment by vindar** [comment]
Just run the script with the command line `python obj_to_h.py` and then follow the instructions... You need a not too old version of Python 3 installed on your computer.

**Comment by Niutonian** [comment]
Forgot to close this issue, thank you for your help
