### ISSUE TITLE
About Arduino_GFX using tgx

### ISSUE THREAD

**Issue by modi12jin** [vindar/tgx#2]
> Use this library

```
https://github.com/moononournation/Arduino_GFX
```

How to transplant them?

**Comment by vindar** [comment]
Hello, 

This library is a bit different from Arduino_GFX (or Adafruit_GFX or TFT_eSPI) because there is not drawing primitive. The driver simply upload a frame buffer to the screen as fast as possible. Also, this lib only works with Teensy 4/4.1 and with an ILI9341 screen... 

If that is indeed what you are looking for, you can look at the examples on how to use it. I just added new examples recently.

**Comment by vindar** [comment]
Hello, 

This library only write on a memory frame-buffer. It does not upload anything to a screen. For that you will need another library. For instance, if you are using a Teensy4/4.1 and an ILI9341 screen, you can use [this one](https://github.com/vindar/ILI9341_T4).

It that is indeed what you want to do, you can look at the examples and into the `Image.h` header file to see how to use the drawing primitives which (I guess) should be quite similar to those in the Arduino_GFX library...

**Comment by modi12jin** [comment]
Can you add an example of using ESP32? I don't know how to use


Can I use these screens only with ST7789V and ILI9488? What work do i need to use them




---Original---
From: "Arvind ***@***.***&gt;
Date: Mon, Aug 23, 2021 08:41 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vindar/tgx] About Arduino_GFX using tgx (#2)




 
Hello,
 
This library only write on a memory frame-buffer. It does not upload anything to a screen. For that you will need another library. For instance, if you are using a Teensy4/4.1 and an ILI9341 screen, you can use this one.
 
It that is indeed what you want to do, you can look at the examples and into the Image.h header file to see how to use the drawing primitives which (I guess) should be quite similar to those in the Arduino_GFX library...
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vindar** [comment]
Hi, 

I just added an example in the library which runs on a ESP32 and uses Bodmer's TFT_eSPI library (https://github.com/Bodmer/TFT_eSPI). I tried it on an IlI9341 screen but it should also work on other screen such as ST7789V. 

You can check the video: https://youtu.be/Jbm-qY-6Whc
