### ISSUE TITLE
Would love to have a fillPolygon method

### ISSUE THREAD

**Issue by rjonkman** [vindar/tgx#22]
Thanks for the wonderful library. I realize I can do it with a series of triangles, but it would be nice to have built in method.

**Comment by vindar** [comment]
Hi, 

I am answering quite late... 

The method `fillPolygon` is available if you switch to the `improved_drawing_primitive`  branch. 
This branch (which will become the master one 'soon') contains a much better and more complete 2D API (for example for drawing pie charts, Beziers curves, Spline...). 

Best,

**Comment by rjonkman** [comment]
Great to hear you're still at it.  I have built an entire UI framework on top of this library. I had borrowed a bunch of code from some other projects to get extra functionality and smoother drawing methods, but I'll definitely check out your new code.
