### ISSUE TITLE
AntiAliased Clock

### ISSUE THREAD

**Issue by DIYLAB-DE** [vindar/tgx#4]
Hi Arvind,

I have played a little bit again ;o)
If you want, you can include the clock in your examples, I would be happy. Code improvements very welcome.

https://github.com/DIYLAB-DE/AntiAliasedClock

Kind regards
Bruno

**Comment by vindar** [comment]
Hi Bruno, 

Very nice. The clocks look really great ! 
I just added it to the tgx examples. Thanks !
