### ISSUE TITLE
Circle segment with antialiasing and rotated font

### ISSUE THREAD

**Issue by DIYLAB-DE** [vindar/tgx#9]
Hi Arvind,

as you can see in the picture, I use fixed background images for my analog display.

![analog](https://user-images.githubusercontent.com/87319037/132170361-f7fd912e-e9d4-48cf-9760-18dfc5e983e1.png)

The goal is to draw the scale itself.
For this it is necessary to draw the circle segments marked with the green arrow with antialiasing.
Is it already possible with the current capabilities of your TGX library?

And if it is possible, how could I draw the font as shown in the picture? Draw on sprites and then rotate them?

Kind regards
Bruno

**Comment by vindar** [comment]
Hi Bruno, 

Unfortunately, there is currently no primitive that allows you to draw (anti-aliased) circle segments. I think it is quite tricky to implement correctly and efficiently so I do not know if/when I will add it to the library.

In fact, even if I add these primitives at some point, I do not think it can give as good results as with images created with a professional image editor (that can use vector graphics and take the time to create very high quality drawing). Furthermore, TGX targets mostly 'real time' rendering so I prefer the drawing primitives to be relatively fast/lightweight... So it might be better to keep using precomputed background images.  Note that as long as you use the usual blit() method (without scaling/rotation), then there is not problem storing the image in flash (PROGMEM) so memory space should not be a problem.  

Of course, I will let you know if I add advanced drawing primitives but it will probably take a little while :-)

Arvind

**Comment by DIYLAB-DE** [comment]
Hi Arvind,

that's how I've been doing it for quite some time, I use 3 background images: black, white, warm.
This of course goes very well and lack of space also do not have, but by the images we have no way to dynamically change the colors, especially the background color.

I played a bit with LVGL and there the circle segments are drawn very clean. Maybe it's worth a look there? ;o)
In the LVGL forum, the drawing method was also discussed at some point, but unfortunately I can't find it again.

Kind regards
Bruno

**Comment by DIYLAB-DE** [comment]
Hi Arvind,

I have drawn two pseudo circle segments with TGX as a test:

```
    im.drawSpot({ 390, 160 }, 240, RGB565_White, 1.0f);
    im.drawSpot({ 395, 160 }, 240, RGB565_Black, 1.0f);

    im.drawSpot({ -150, 160 }, 240, RGB565_White, 1.0f);
    im.drawSpot({ -155, 160 }, 240, RGB565_Black, 1.0f);

    im.fillRect(0, 0, 240, 30, RGB565_Black, 1.0f);
    im.fillRect(0, 320 - 30, 240, 30, RGB565_Black, 1.0f);
```
This really does not look so good:

![pseudocircle](https://user-images.githubusercontent.com/87319037/132463912-fc71687d-aef6-4151-991f-c14e86cc39c2.jpg)

And here is a section with LVGL:

![lvgl](https://user-images.githubusercontent.com/87319037/132464120-d8dacfa8-8ca5-430b-88d9-68d922ad0ed0.jpg)

I could live with that very well :o)
Dream ...

Kind regards
Bruno
